### ISSUE TITLE
Can't access the VAB

### ISSUE THREAD

**Issue by RemonKewl** [bongotastic/Headlines#166] opened 2021-11-06 07:19 UTC
Started with the newest version, 0.11.4. Rolling back helped.

**Comment by bongotastic** [comment] 2021-11-06 11:45
Thanks for reporting.  This is something that I cant reproduce on my own, would you be able to share your Ksp log file when this happens?

**Comment by bongotastic** [comment] 2021-11-06 11:59
Is this affecting all scene changes, saving and leaving KSP? Is this issue only on existing saves, or new ones as well?

**Comment by RemonKewl** [comment] 2021-11-06 12:59
[Player.log](https://github.com/bongotastic/Headlines/files/7490485/Player.log)
I can get in research and mission control but can't get back out. I can't access the menu from the top right button, but I can if I press escape. I can't get out of the game from the menu though, the button does nothing.

**Comment by bongotastic** [comment] 2021-11-06 14:25
Thanks. I will look at this tomorrow.

**Comment by RemonKewl** [comment] 2021-11-06 18:23
Also, the R&D points I get from my scientists aren't improving my tech times. Is that how it should work?

**Comment by bongotastic** [comment] 2021-11-06 18:26
You should see a change in rate when the points change.  However, if you have multiple KSCs, then this is possible.  Headlines isn't accounting for multiple sites yet.

**Comment by RemonKewl** [comment] 2021-11-06 18:29
Nope, not multiple KSCs. I have 3 points in R&D and still have 2.5 sci/yr, the starting rate
![headlines1](https://user-images.githubusercontent.com/25742029/140620110-6d117b5e-b534-42e1-94dc-e82312a07f09.jpg)
.

**Comment by bongotastic** [comment] 2021-11-06 18:34
Odd, ill checkthis out as a new issue.

**Comment by bongotastic** [comment] 2021-11-07 11:35
@RemonKewl , the science rate issue was definitely an issue and it is fixed. *Sometimes* the rate in the upgrade window isn't reflecting the rate in the tech nodes, but the rates are correct where it matters and it somehow fixes itself shortly thereafter. I also realized that something similar was at play for build rates. So, a big thank you for bringing this up.

**Comment by bongotastic** [comment] 2021-11-07 11:53
Both issues are fixed in v0.11.5. Can you confirm that this is the case for the original issue about scene switch and exiting KSP?

**Comment by RemonKewl** [comment] 2021-11-07 13:25
Everything works ok from what I can tell.

**Closed** 2021-11-07 14:51 UTC
Labels: bug, testing needed
